/*1. CREACION DE BASE DE DATOS*/
CREATE DATABASE CITASWEB;
USE CITASWEB;
/*CREACION DE USUARIO ADMINISTRADOR*/
CREATE USER ADMIN identified by "Clave123*";
/*CREATE USER PARA CONEXION DESDE EL API REST. ESTO CON EL FIN DE LIMITAR PERMISOS*/
CREATE USER SWCITASWEB identified BY "16oIc9xcFAl6";